ALTER TABLE runs
    ADD COLUMN origin VARCHAR(20) NOT NULL DEFAULT 'IMPORT',
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
    ADD COLUMN min_lat DOUBLE PRECISION,
    ADD COLUMN min_lng DOUBLE PRECISION,
    ADD COLUMN max_lat DOUBLE PRECISION,
    ADD COLUMN max_lng DOUBLE PRECISION;

UPDATE runs
SET status = 'VALIDATED';

ALTER TABLE runs
    ALTER COLUMN status SET DEFAULT 'RECEIVED';

ALTER TABLE runs
    ADD CONSTRAINT check_run_origin CHECK (origin IN ('IOS', 'WEB', 'IMPORT')),
    ADD CONSTRAINT check_run_status CHECK (status IN ('RECEIVED', 'VALIDATED', 'REJECTED'));
